### ISSUE TITLE
tantivy 0.15 doc store iter panics when first doc in checkpoint is deleted

### ISSUE THREAD

**Issue by PSeitz** [quickwit-oss/tantivy#1077]
The store reader raw document iterator fails when the first document of a block past a new checkpoint has been deleted. This was caused by the `reset_block_pos flag` used to reset `block_start_pos` being discarded when the current document isn't alive.

If the `block_start_pos` is incorrect, the reader reads data at the wrong position. The first information it tries to read is the document length, which is Vint encoded. This may fail with an 'attempt to shift left with overflow' if all bytes have the high bit set. It may also succeed with a random number, which will then cause an out of bounds error like `range start index 14171 out of range for slice of length 4218` or the document parsing fails afterwards.

Will be fixed by #1076 

Below are stack traces which are caused by the issue (Note that the error 'You forgot to flush "00000050000000000000000000000000.fast" before its writter got Drop is shown for all unexpected failures during merge)

```
      thread 'merge_thread2' panicked at 'attempt to shift left with overflow', src/common/vint.rs:157:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'merge_thread2' panicked at 'You forgot to flush "00000059000000000000000000000000.fast" before its writter got Drop. Do not rely on drop.', src/directory/ram_directory.rs:48:13
stack backtrace:
   0:     0x5562d9229b80 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5562d9229b80 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5562d9229b80 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5562d9229b80 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5562d924d20f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x5562d9225da2 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x5562d922c3b5 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5562d922c3b5 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5562d922c3b5 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x5562d922be63 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x5562d922c9bd - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x5562d922c557 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  12:     0x5562d922a03c - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5562d922c4b9 - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:     0x5562d82d234b - std::panicking::begin_panic_fmt::h400b8e9dca200408
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
  15:     0x5562d87bf2e5 - <tantivy::directory::ram_directory::VecWriter as core::ops::drop::Drop>::drop::h6878c4523a4d7fca
                               at /home/appaquet/Projects/exomind/tantivy/src/directory/ram_directory.rs:48:13
  16:     0x5562d8608163 - core::ptr::drop_in_place<tantivy::directory::ram_directory::VecWriter>::hde8f4cab659209a1
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  17:     0x5562d8615fbd - core::ptr::drop_in_place<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>::h5e9544df7732d4be
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  18:     0x5562d85ed232 - core::ptr::drop_in_place<core::option::Option<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>>::h1f2b7491c646f620
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  19:     0x5562d85f110e - core::ptr::drop_in_place<tantivy::directory::footer::FooterProxy<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>>::h513428e94832053f
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  20:     0x5562d8615fbd - core::ptr::drop_in_place<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>::h5e9544df7732d4be
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  21:     0x5562d85ed232 - core::ptr::drop_in_place<core::option::Option<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>>::h1f2b7491c646f620
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  22:     0x5562d85f10de - core::ptr::drop_in_place<std::io::buffered::bufwriter::BufWriter<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>>::h727343086f01b352
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  23:     0x5562d85f8d4a - core::ptr::drop_in_place<tantivy::common::counting_writer::CountingWriter<std::io::buffered::bufwriter::BufWriter<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>>>::h178dfaaae1002fc3
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  24:     0x5562d85f89e3 - core::ptr::drop_in_place<tantivy::common::composite_file::CompositeWrite<std::io::buffered::bufwriter::BufWriter<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>>>::h2c3ecef074866380
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  25:     0x5562d8611b1a - core::ptr::drop_in_place<tantivy::fastfield::serializer::CompositeFastFieldSerializer>::h77feddd18185ce28
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  26:     0x5562d860e799 - core::ptr::drop_in_place<tantivy::indexer::segment_serializer::SegmentSerializer>::h04fbde7b9baf895f
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  27:     0x5562d87b3bb3 - <tantivy::indexer::merger::IndexMerger as tantivy::core::segment::SerializableSegment>::write::h4b890052a0d44da7
                               at /home/appaquet/Projects/exomind/tantivy/src/indexer/merger.rs:1086:5
  28:     0x5562d84e526e - tantivy::indexer::segment_updater::merge::hff285369716234c2
                               at /home/appaquet/Projects/exomind/tantivy/src/indexer/segment_updater.rs:143:20
  29:     0x5562d84ec69e - tantivy::indexer::segment_updater::SegmentUpdater::start_merge::{{closure}}::h03e5d2c2c49c3b28
                               at /home/appaquet/Projects/exomind/tantivy/src/indexer/segment_updater.rs:499:19
  30:     0x5562d879f819 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h63fae4fe96e748b2
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  31:     0x5562d8f64aa9 - <futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll::h61fcd9b25012e760
                               at /home/appaquet/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.15/src/future_obj.rs:84:18
  32:     0x5562d8f649c1 - <futures_task::future_obj::FutureObj<T> as core::future::future::Future>::poll::h9560f34665590ade
                               at /home/appaquet/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.15/src/future_obj.rs:127:9
  33:     0x5562d8f6271c - futures_util::future::future::FutureExt::poll_unpin::h350f3c84c64b20cc
                               at /home/appaquet/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/future/mod.rs:562:9
  34:     0x5562d8f5aed5 - futures_executor::thread_pool::Task::run::h682c328f718cecbb
                               at /home/appaquet/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.15/src/thread_pool.rs:322:27
  35:     0x5562d8f59d4e - futures_executor::thread_pool::PoolState::work::h1286e6b3b8b3fadc
                               at /home/appaquet/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.15/src/thread_pool.rs:154:39
  36:     0x5562d8f5ad5b - futures_executor::thread_pool::ThreadPoolBuilder::create::{{closure}}::hc1a265a5e876813e
                               at /home/appaquet/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.15/src/thread_pool.rs:284:42
  37:     0x5562d8f6274c - std::sys_common::backtrace::__rust_begin_short_backtrace::hedfda90a80be2ef3
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  38:     0x5562d8f66901 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hfab5b122f1b68fce
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:474:17
  39:     0x5562d8f62511 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hcb4eed3a60795f88
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  40:     0x5562d8f53da3 - std::panicking::try::do_call::h6041e604c2f21e41
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  41:     0x5562d8f5410d - __rust_try
  42:     0x5562d8f53ce1 - std::panicking::try::hb7b4f3f7a3897a2b
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  43:     0x5562d8f62871 - std::panic::catch_unwind::hb91d72f001ce0138
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  44:     0x5562d8f666fd - std::thread::Builder::spawn_unchecked::{{closure}}::h8defec4a24e15fc8
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:473:30
  45:     0x5562d8f629af - core::ops::function::FnOnce::call_once{{vtable.shim}}::h43e47fe71e7ac956
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  46:     0x5562d923334a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc444a77f8dd8d825
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
  47:     0x5562d923334a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8b68a0a9a2093dfc
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
  48:     0x5562d923334a - std::sys::unix::thread::Thread::new::thread_start::hb95464447f61f48d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys/unix/thread.rs:71:17
  49:     0x7f256ca6b609 - start_thread
  50:     0x7f256c83d293 - clone
  51:                0x0 - <unknown>
```
      

```
thread 'merge_thread1' panicked at 'range start index 14171 out of range for slice of length 4218', src/store/reader.rs:214:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'merge_thread1' panicked at 'You forgot to flush "00000050000000000000000000000000.fast" before its writter got Drop. Do not rely on drop.', src/directory/ram_directory.rs:48:13
stack backtrace:
   0:     0x5647b269cb80 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5647b269cb80 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5647b269cb80 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5647b269cb80 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5647b26c020f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x5647b2698da2 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x5647b269f3b5 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5647b269f3b5 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5647b269f3b5 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x5647b269ee63 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x5647b269f9bd - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x5647b269f557 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  12:     0x5647b269d03c - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5647b269f4b9 - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:     0x5647b174534b - std::panicking::begin_panic_fmt::h400b8e9dca200408
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
  15:     0x5647b1c322e5 - <tantivy::directory::ram_directory::VecWriter as core::ops::drop::Drop>::drop::h6878c4523a4d7fca
                               at /home/appaquet/Projects/exomind/tantivy/src/directory/ram_directory.rs:48:13
  16:     0x5647b1a7b163 - core::ptr::drop_in_place<tantivy::directory::ram_directory::VecWriter>::hde8f4cab659209a1
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  17:     0x5647b1a88fbd - core::ptr::drop_in_place<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>::h5e9544df7732d4be
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  18:     0x5647b1a60232 - core::ptr::drop_in_place<core::option::Option<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>>::h1f2b7491c646f620
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  19:     0x5647b1a6410e - core::ptr::drop_in_place<tantivy::directory::footer::FooterProxy<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>>::h513428e94832053f
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  20:     0x5647b1a88fbd - core::ptr::drop_in_place<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>::h5e9544df7732d4be
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  21:     0x5647b1a60232 - core::ptr::drop_in_place<core::option::Option<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>>::h1f2b7491c646f620
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  22:     0x5647b1a640de - core::ptr::drop_in_place<std::io::buffered::bufwriter::BufWriter<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>>::h727343086f01b352
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  23:     0x5647b1a6bd4a - core::ptr::drop_in_place<tantivy::common::counting_writer::CountingWriter<std::io::buffered::bufwriter::BufWriter<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>>>::h178dfaaae1002fc3
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  24:     0x5647b1a6b9e3 - core::ptr::drop_in_place<tantivy::common::composite_file::CompositeWrite<std::io::buffered::bufwriter::BufWriter<alloc::boxed::Box<dyn tantivy::directory::TerminatingWrite>>>>::h2c3ecef074866380
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  25:     0x5647b1a84b1a - core::ptr::drop_in_place<tantivy::fastfield::serializer::CompositeFastFieldSerializer>::h77feddd18185ce28
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  26:     0x5647b1a81799 - core::ptr::drop_in_place<tantivy::indexer::segment_serializer::SegmentSerializer>::h04fbde7b9baf895f
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  27:     0x5647b1c26bb3 - <tantivy::indexer::merger::IndexMerger as tantivy::core::segment::SerializableSegment>::write::h4b890052a0d44da7
                               at /home/appaquet/Projects/exomind/tantivy/src/indexer/merger.rs:1086:5
  28:     0x5647b195826e - tantivy::indexer::segment_updater::merge::hff285369716234c2
                               at /home/appaquet/Projects/exomind/tantivy/src/indexer/segment_updater.rs:143:20
  29:     0x5647b195f69e - tantivy::indexer::segment_updater::SegmentUpdater::start_merge::{{closure}}::h03e5d2c2c49c3b28
                               at /home/appaquet/Projects/exomind/tantivy/src/indexer/segment_updater.rs:499:19
  30:     0x5647b1c12819 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h63fae4fe96e748b2
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  31:     0x5647b23d7aa9 - <futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll::h61fcd9b25012e760
                               at /home/appaquet/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.15/src/future_obj.rs:84:18
  32:     0x5647b23d79c1 - <futures_task::future_obj::FutureObj<T> as core::future::future::Future>::poll::h9560f34665590ade
                               at /home/appaquet/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.15/src/future_obj.rs:127:9
  33:     0x5647b23d571c - futures_util::future::future::FutureExt::poll_unpin::h350f3c84c64b20cc
                               at /home/appaquet/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/future/mod.rs:562:9
  34:     0x5647b23cded5 - futures_executor::thread_pool::Task::run::h682c328f718cecbb
                               at /home/appaquet/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.15/src/thread_pool.rs:322:27
  35:     0x5647b23ccd4e - futures_executor::thread_pool::PoolState::work::h1286e6b3b8b3fadc
                               at /home/appaquet/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.15/src/thread_pool.rs:154:39
  36:     0x5647b23cdd5b - futures_executor::thread_pool::ThreadPoolBuilder::create::{{closure}}::hc1a265a5e876813e
                               at /home/appaquet/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.15/src/thread_pool.rs:284:42
  37:     0x5647b23d574c - std::sys_common::backtrace::__rust_begin_short_backtrace::hedfda90a80be2ef3
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  38:     0x5647b23d9901 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hfab5b122f1b68fce
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:474:17
  39:     0x5647b23d5511 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hcb4eed3a60795f88
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  40:     0x5647b23c6da3 - std::panicking::try::do_call::h6041e604c2f21e41
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  41:     0x5647b23c710d - __rust_try
  42:     0x5647b23c6ce1 - std::panicking::try::hb7b4f3f7a3897a2b
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  43:     0x5647b23d5871 - std::panic::catch_unwind::hb91d72f001ce0138
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  44:     0x5647b23d96fd - std::thread::Builder::spawn_unchecked::{{closure}}::h8defec4a24e15fc8
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:473:30
  45:     0x5647b23d59af - core::ops::function::FnOnce::call_once{{vtable.shim}}::h43e47fe71e7ac956
                               at /home/appaquet/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  46:     0x5647b26a634a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc444a77f8dd8d825
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
  47:     0x5647b26a634a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8b68a0a9a2093dfc
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/boxed.rs:1546:9
  48:     0x5647b26a634a - std::sys::unix::thread::Thread::new::thread_start::hb95464447f61f48d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys/unix/thread.rs:71:17
  49:     0x7f25509c4609 - start_thread
  50:     0x7f2550796293 - clone
  51:                0x0 - <unknown>
```

**Comment by fulmicoton** [comment]
Fixed published as Tantivy 15.1
