### ISSUE TITLE
panic in tokenizer when indexing large amount of documents

### ISSUE THREAD

**Issue by pwoolcoc** [quickwit-oss/tantivy#364]
I'm getting an "attempt to add with overflow" panic after indexing ~3000 documents:

```
paul@paul-solus ~> rustc --version
rustc 1.30.0-nightly (73c78734b 2018-08-05)
paul@paul-solus ~> rg 'tantivy' Cargo.toml 
15:tantivy = { git = "https://github.com/tantivy-search/tantivy" }
```

```                                                                                                               
thread 'indexing thread 116 for gen 0' panicked at 'attempt to add with overflow', /home/paul/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/d056ae6/src/tokenizer/token_stream_chain.rs:47:39
stack backtrace:                                                                                                                         
   0:     0x562f174ff3de - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h030c686d04dfe25d                                                                        
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49                                                  
   1:     0x562f174f0986 - std::sys_common::backtrace::print::hcaaa8a33e22399b5                  
                               at libstd/sys_common/backtrace.rs:71                                                              
                               at libstd/sys_common/backtrace.rs:59                                         
   2:     0x562f174eccad - std::panicking::default_hook::{{closure}}::h24caa4959bb4aa20                                               
                               at libstd/panicking.rs:211                                                             
   3:     0x562f174eca20 - std::panicking::default_hook::h71f42d8932f05cd8                                                           
                               at libstd/panicking.rs:227                                                  
   4:     0x562f174ed31c - std::panicking::rust_panic_with_hook::hfff47c1711fd8ff7                                                  
                               at libstd/panicking.rs:475                                    
   5:     0x562f174ecf19 - std::panicking::continue_panic_fmt::h502e8367a34413d0                                                  
                               at libstd/panicking.rs:390                                                                  
   6:     0x562f174ece15 - rust_begin_unwind                                                                                      
                               at libstd/panicking.rs:325                                             
   7:     0x562f1754504b - core::panicking::panic_fmt::h3e50b231b068ce67          
                               at libcore/panicking.rs:77                                          
   8:     0x562f17544f7a - core::panicking::panic::h8f7e3a726cb6c026    
                               at libcore/panicking.rs:52                                                                    
   9:     0x562f16607d1e - <tantivy::tokenizer::token_stream_chain::TokenStreamChain<TTokenStream> as tantivy::tokenizer::tokenizer::TokenStream>::advance::h2de472c27afc3750
                               at /home/paul/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/d056ae6/src/tokenizer/token_stream_chain.rs:47
  10:     0x562f1656c6ed - <alloc::boxed::Box<(dyn tantivy::tokenizer::tokenizer::TokenStream + 'b)> as tantivy::tokenizer::tokenizer::TokenStream>::advance::h0428225c5a4e264c
                               at /home/paul/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/d056ae6/src/tokenizer/tokenizer.rs:140  
  11:     0x562f1656c884 - tantivy::tokenizer::tokenizer::TokenStream::process::h14b4354f33489c7e
                               at /home/paul/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/d056ae6/src/tokenizer/tokenizer.rs:228
  12:     0x562f1658a5f2 - tantivy::postings::postings_writer::PostingsWriter::index_text::he099f858bf70dde8
                               at /home/paul/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/d056ae6/src/postings/postings_writer.rs:210
  13:     0x562f165892a8 - tantivy::postings::postings_writer::MultiFieldPostingsWriter::index_text::hbdf257fe10a58182
                               at /home/paul/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/d056ae6/src/postings/postings_writer.rs:76
  14:     0x562f16465b68 - tantivy::indexer::segment_writer::SegmentWriter::add_document::h878e94aaf49c68e8
                               at /home/paul/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/d056ae6/src/indexer/segment_writer.rs:155
  15:     0x562f16645aad - tantivy::indexer::index_writer::index_documents::h76b1e289b857ff64        
                               at /home/paul/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/d056ae6/src/indexer/index_writer.rs:274
  16:     0x562f166466c1 - tantivy::indexer::index_writer::IndexWriter::add_indexing_worker::{{closure}}::h54c73e6db7b34dc2
                               at /home/paul/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/d056ae6/src/indexer/index_writer.rs:407
  17:     0x562f164db4bb - std::sys_common::backtrace::__rust_begin_short_backtrace::heb512bd8d7ad7dae
                               at /checkout/src/libstd/sys_common/backtrace.rs:136
```

**Comment by fulmicoton** [comment]
Thanks for the report. I think I know what the problem might be.

**Comment by fulmicoton** [comment]
Happens because of the implementation of default for Token. 
If the first fieldValue yields no token at all, then we end up trying to add 2 to `usize::max_value()`.


https://github.com/tantivy-search/tantivy/blob/d056ae60dc565477fe5332362ccb1862d4e9a10c/src/tokenizer/tokenizer.rs#L27

https://github.com/tantivy-search/tantivy/blob/d056ae60dc565477fe5332362ccb1862d4e9a10c/src/tokenizer/token_stream_chain.rs#L47

**Comment by fulmicoton** [comment]
@pwoolcoc A fix is on the way on https://github.com/tantivy-search/tantivy/tree/issues/364 . I won't merge it until tonight but you can point at the given revision if you are blocked right now.

The number of documents is not an issue at all. Feel free to index millions of documents at a time. Tantivy should not exceed the RAM budget you give it by much.

**Comment by pwoolcoc** [comment]
thanks so much! I didn't think the number of documents was too high, but it did always seem to error out at the same place, so I wasn't sure what was wrong.

thanks for the quick fix!

**Comment by fulmicoton** [comment]
Somehow travis-ci seem to choke on the new version of combine. That's strange the same version of rustc compiles tantivy without any problem on my machine. I hope it works ok on your setup.

**Comment by pwoolcoc** [comment]
OK, I should be able to test it in a few minutes and let you know, thanks again

**Comment by pwoolcoc** [comment]
I did get the issue with combine, this seemed to fix it but I'm not sure if it's the "right" fix:

```
diff --git a/src/lib.rs b/src/lib.rs
index d3b1ff771..2db8a4352 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -7,6 +7,7 @@
 #![allow(new_without_default)]
 #![allow(decimal_literal_representation)]
 #![warn(missing_docs)]
+#![recursion_limit="1024"]
 
 //! # `tantivy`
 //!
```

**Comment by pwoolcoc** [comment]
also, the fix in issues/364 works perfectly for me \o/

**Comment by fulmicoton** [comment]
I raised the recursion limit in master (thanks for giving me the solution :) ) and merged the bug fix.
