### ISSUE TITLE
Index out of bound error in LogMergePolicy

### ISSUE THREAD

**Issue by ppodolsky** [quickwit-oss/tantivy#828]
**Describe the bug**
- What did you do?
Adding a lot of documents in bulks of size 100 000 without calling `commit` for a long time.
- What happened?
Index out of bounds
- What was expected?
Something other :)

**Backtrace**

```
thread 'segment_updater0' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/slice/mod.rs:2842:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:63
  14: <usize as core::slice::SliceIndex<[T]>>::index
  15: core::slice::<impl core::ops::index::Index<I> for [T]>::index
  16: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
  17: <tantivy::indexer::log_merge_policy::LogMergePolicy as tantivy::indexer::merge_policy::MergePolicy>::compute_merge_candidates
  18: tantivy::indexer::segment_updater::SegmentUpdater::consider_merge_options::{{closure}}
  19: <std::future::GenFuture<T> as core::future::future::Future>::poll
  20: std::future::poll_with_tls_context
  21: tantivy::indexer::segment_updater::SegmentUpdater::schedule_add_segment::{{closure}}
  22: <std::future::GenFuture<T> as core::future::future::Future>::poll
  23: std::future::poll_with_tls_context
  24: tantivy::indexer::segment_updater::SegmentUpdater::schedule_future::{{closure}}
  25: <std::future::GenFuture<T> as core::future::future::Future>::poll
  26: <futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll
  27: <futures_task::future_obj::FutureObj<T> as core::future::future::Future>::poll
  28: futures_util::future::future::FutureExt::poll_unpin
  29: futures_executor::thread_pool::Task::run
  30: futures_executor::thread_pool::PoolState::work
  31: futures_executor::thread_pool::ThreadPoolBuilder::create::{{closure}}
```

**Which version of tantivy are you using?**
c55db83. The reason is still in master: https://github.com/tantivy-search/tantivy/blob/master/src/indexer/log_merge_policy.rs#L75

**To Reproduce**

I could provide if it is needed, but my code required cleaning. Hope it is obvious enough without reproducing code. [size_sorted_tuples](https://github.com/tantivy-search/tantivy/blob/master/src/indexer/log_merge_policy.rs#L75) is empty after filtering for some reasons.

**Comment by fulmicoton** [comment]
Thank you very much. I had no problem reproducing. It happens if you end up with all of your segments higher than the largest segment that can be considered for merge.

The fix is on the way.

**Comment by ppodolsky** [comment]
Thank you for the rapid response and, taking my time, would like to thank for this masterpiece in the land of Rust:) I really like it and the way you are developing it.

**Comment by fulmicoton** [comment]
@ppodolsky That's super kind of you :) ! Thank you
