### ISSUE TITLE
Index out of bounds on conjunction of term and range queries

### ISSUE THREAD

**Issue by ppodolsky** [quickwit-oss/tantivy#857]
**Describe the bug**
- What did you do?
I did a search `hemoglobin AND year:[2004 TO 2008]`
- What happened?
```
thread 'thrd-tantivy-search-1' panicked at 'index out of bounds: the len is 503444 but the index is 33554431', nexus/tantivy/src/common/bitset.rs:197:9
stack backtrace:
   0:     0x562ec859cc25 - backtrace::backtrace::libunwind::trace::h396c07d2071b43af
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x562ec859cc25 - backtrace::backtrace::trace_unsynchronized::h7aa0e4bb23d9c158
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x562ec859cc25 - std::sys_common::backtrace::_print_fmt::hd15ac5d4adcd355b
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x562ec859cc25 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hec5354be8ccc3ecc
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x562ec85c60dc - core::fmt::write::h3d34909eeb4f225b
                               at src/libcore/fmt/mod.rs:1076
   5:     0x562ec8596053 - std::io::Write::write_fmt::h1da287b3de55ed16
                               at src/libstd/io/mod.rs:1537
   6:     0x562ec859f8e0 - std::sys_common::backtrace::_print::h4d206838e1ace354
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x562ec859f8e0 - std::sys_common::backtrace::print::h1f778e9940ee5977
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x562ec859f8e0 - std::panicking::default_hook::{{closure}}::h704403a56cbf5783
                               at src/libstd/panicking.rs:198
   9:     0x562ec859f62c - std::panicking::default_hook::ha4567a10dec4ef8d
                               at src/libstd/panicking.rs:218
  10:     0x562ec859ff17 - std::panicking::rust_panic_with_hook::h88a1f16ec8a7bb20
                               at src/libstd/panicking.rs:486
  11:     0x562ec859fb1b - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  12:     0x562ec85c4011 - core::panicking::panic_fmt::hbddb7fe6f399b81a
                               at src/libcore/panicking.rs:101
  13:     0x562ec85c3fd2 - core::panicking::panic_bounds_check::ha5d508118eb53f4e
                               at src/libcore/panicking.rs:73
  14:     0x562ec7b223a8 - tantivy::common::bitset::BitSet::tinyset::hdd87f22745a4601b
  15:     0x562ec7c86fe7 - tantivy::query::bitset::BitSetDocSet::go_to_bucket::h95d840c725e31291
  16:     0x562ec7c8748b - <tantivy::query::bitset::BitSetDocSet as tantivy::docset::DocSet>::seek::h8d724c51cd067383
  17:     0x562ec7bb5187 - <tantivy::query::scorer::ConstScorer<TDocSet> as tantivy::docset::DocSet>::seek::h83569c7dad68fa42
  18:     0x562ec7d003d9 - <alloc::boxed::Box<TDocSet> as tantivy::docset::DocSet>::seek::h9a83f6879d49a537
  19:     0x562ec7b851c5 - <tantivy::query::intersection::Intersection<TDocSet,TOtherDocSet> as tantivy::docset::DocSet>::advance::h695e5eace260a9d9
  20:     0x562ec7d003a1 - <alloc::boxed::Box<TDocSet> as tantivy::docset::DocSet>::advance::h322fda5b3ca6c42e
  21:     0x562ec7c36442 - tantivy::query::union::refill::{{closure}}::hf5a373e45ad7ff93
  22:     0x562ec7c34604 - tantivy::query::union::unordered_drain_filter::h6e7b68f0b22ab1c5
  23:     0x562ec7c35b9b - tantivy::query::union::refill::hea31c9e6bbf7ebe6
  24:     0x562ec7c3665e - tantivy::query::union::Union<TScorer,TScoreCombiner>::refill::h98a3ae4aac0bd6e7
  25:     0x562ec7c374a8 - <tantivy::query::union::Union<TScorer,TScoreCombiner> as tantivy::docset::DocSet>::advance::h21ef922c6ca3d0c9
  26:     0x562ec7c88a45 - tantivy::query::weight::for_each_pruning_scorer::h93230e6eeccfbbf8
  27:     0x562ec7b83828 - <tantivy::query::boolean_query::boolean_weight::BooleanWeight as tantivy::query::weight::Weight>::for_each_pruning::hcf61c9c5261e3323
  28:     0x562ec78ebb35 - <api::search_engine::classic::top_collector::ClassicTopCollector as tantivy::collector::Collector>::collect_segment::hf5a82523db668d4e
  29:     0x562ec7954035 - tantivy::core::searcher::Searcher::search_with_executor::{{closure}}::h4c556ef367a0e167
  30:     0x562ec79af244 - tantivy::core::executor::Executor::map::{{closure}}::{{closure}}::h1a7d8608ae8b7d51
  31:     0x562ec7927c5a - rayon_core::scope::Scope::spawn::{{closure}}::{{closure}}::he9f4fa8f0e3f9d88
  32:     0x562ec795a861 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb26ed7052a6210fd
  33:     0x562ec792c1b7 - std::panicking::try::do_call::h386125dab48ce4f8
  34:     0x562ec793c03d - __rust_try
  35:     0x562ec792afbc - std::panicking::try::h0074d2d4ed8ca23c
  36:     0x562ec795f183 - std::panic::catch_unwind::h25f2f55d62ccff6d
  37:     0x562ec79a0bd0 - rayon_core::unwind::halt_unwinding::hdc9fa95767473962
  38:     0x562ec7928273 - rayon_core::scope::ScopeBase::execute_job_closure::hfc8dd90d6e5610f4
  39:     0x562ec7927ff3 - rayon_core::scope::ScopeBase::execute_job::hf2ad401ee9558ea0
  40:     0x562ec7927b50 - rayon_core::scope::Scope::spawn::{{closure}}::h7fbddf4c30c6fa66
  41:     0x562ec7910ea0 - <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute::h9fc717a4be459fe6
  42:     0x562ec7ef9f7a - rayon_core::job::JobRef::execute::he05b3a828cf3180c
  43:     0x562ec7eee1d0 - rayon_core::registry::WorkerThread::execute::h39978e106fa9aee3
  44:     0x562ec7eedf69 - rayon_core::registry::WorkerThread::wait_until_cold::hddc9141b38d23114
  45:     0x562ec7eedd51 - rayon_core::registry::WorkerThread::wait_until::h1f071a720f74886b
  46:     0x562ec7eee96c - rayon_core::registry::main_loop::h0779a594efce4596
  47:     0x562ec7eebee0 - rayon_core::registry::ThreadBuilder::run::h0f55c4581c3ef739
  48:     0x562ec7eec3c1 - <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}::h260282579e9cdd9a
  49:     0x562ec7f05620 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdfa45e30ca774009
  50:     0x562ec7efdc41 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hc00c1b2a4bfda637
  51:     0x562ec7eef243 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he33d631fa919e4e4
  52:     0x562ec7ef22ea - std::panicking::try::do_call::ha8f9f82dcfa1aca3
  53:     0x562ec7ef342d - __rust_try
  54:     0x562ec7ef215c - std::panicking::try::hb23236c4c25e74d1
  55:     0x562ec7eefd23 - std::panic::catch_unwind::h6eb96cb948319564
  56:     0x562ec7efda3b - std::thread::Builder::spawn_unchecked::{{closure}}::hb1d8e65d25dc32b5
  57:     0x562ec7ef5bb7 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1fa125ec4e37baf4
  58:     0x562ec85a466a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hcf205bcf9b46c587
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
  59:     0x562ec85a466a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2d53e2246128f5d8
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
  60:     0x562ec85a466a - std::sys::unix::thread::Thread::new::thread_start::h3b6d8a0cd87a87c6
                               at src/libstd/sys/unix/thread.rs:87
  61:     0x7fc6867af609 - start_thread
  62:     0x7fc6866bb103 - __clone
  63:                0x0 - <unknown>
```
- What was expected?
Expected to work like a charm :)
**Which version of tantivy are you using?**
This boy 8e74bb98b59d73a38ba4bcdcb969b69ba1dab42e

**To Reproduce**

I can provide on your request.

UPD.: Rebased on your master, the issue is still here.

**Comment by ppodolsky** [comment]
I've just realized that the issue could be at my side as I'm using my own top_collector :( I will check it. My own top collector is definitely same as yours, but it modifies score (multiplies it by value from fast_field).

**Comment by ppodolsky** [comment]
I've rewritten my top collector using tweak_score_top_collector, the bug is still here.
```
thread 'thrd-tantivy-search-43' panicked at 'index out of bounds: the len is 938132 but the index is 33554431', nexus/tantivy/src/common/bitset.rs:197:9
stack backtrace:
   0:     0x55cc785363a5 - backtrace::backtrace::libunwind::trace::h396c07d2071b43af
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55cc785363a5 - backtrace::backtrace::trace_unsynchronized::h7aa0e4bb23d9c158
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55cc785363a5 - std::sys_common::backtrace::_print_fmt::hd15ac5d4adcd355b
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55cc785363a5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hec5354be8ccc3ecc
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55cc7855f85c - core::fmt::write::h3d34909eeb4f225b
                               at src/libcore/fmt/mod.rs:1076
   5:     0x55cc7852f7d3 - std::io::Write::write_fmt::h1da287b3de55ed16
                               at src/libstd/io/mod.rs:1537
   6:     0x55cc78539060 - std::sys_common::backtrace::_print::h4d206838e1ace354
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55cc78539060 - std::sys_common::backtrace::print::h1f778e9940ee5977
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55cc78539060 - std::panicking::default_hook::{{closure}}::h704403a56cbf5783
                               at src/libstd/panicking.rs:198
   9:     0x55cc78538dac - std::panicking::default_hook::ha4567a10dec4ef8d
                               at src/libstd/panicking.rs:218
  10:     0x55cc78539697 - std::panicking::rust_panic_with_hook::h88a1f16ec8a7bb20
                               at src/libstd/panicking.rs:486
  11:     0x55cc7853929b - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  12:     0x55cc7855d791 - core::panicking::panic_fmt::hbddb7fe6f399b81a
                               at src/libcore/panicking.rs:101
  13:     0x55cc7855d752 - core::panicking::panic_bounds_check::ha5d508118eb53f4e
                               at src/libcore/panicking.rs:73
  14:     0x55cc77abb638 - tantivy::common::bitset::BitSet::tinyset::hdd87f22745a4601b
  15:     0x55cc77c202d7 - tantivy::query::bitset::BitSetDocSet::go_to_bucket::h95d840c725e31291
  16:     0x55cc77c2077b - <tantivy::query::bitset::BitSetDocSet as tantivy::docset::DocSet>::seek::h8d724c51cd067383
  17:     0x55cc77b4e457 - <tantivy::query::scorer::ConstScorer<TDocSet> as tantivy::docset::DocSet>::seek::h83569c7dad68fa42
  18:     0x55cc77c99b59 - <alloc::boxed::Box<TDocSet> as tantivy::docset::DocSet>::seek::h9a83f6879d49a537
  19:     0x55cc77b1e455 - <tantivy::query::intersection::Intersection<TDocSet,TOtherDocSet> as tantivy::docset::DocSet>::advance::h695e5eace260a9d9
  20:     0x55cc77c99b21 - <alloc::boxed::Box<TDocSet> as tantivy::docset::DocSet>::advance::h322fda5b3ca6c42e
  21:     0x55cc77bcf732 - tantivy::query::union::refill::{{closure}}::hf5a373e45ad7ff93
  22:     0x55cc77bcd8f4 - tantivy::query::union::unordered_drain_filter::h6e7b68f0b22ab1c5
  23:     0x55cc77bcee8b - tantivy::query::union::refill::hea31c9e6bbf7ebe6
  24:     0x55cc77bcf94e - tantivy::query::union::Union<TScorer,TScoreCombiner>::refill::h98a3ae4aac0bd6e7
  25:     0x55cc77bd0798 - <tantivy::query::union::Union<TScorer,TScoreCombiner> as tantivy::docset::DocSet>::advance::h21ef922c6ca3d0c9
  26:     0x55cc77c21b36 - tantivy::query::weight::for_each_scorer::habb6c1ba998c7db9
  27:     0x55cc77b1c65e - <tantivy::query::boolean_query::boolean_weight::BooleanWeight as tantivy::query::weight::Weight>::for_each::h3fd88479d3732c8d
  28:     0x55cc7793698c - tantivy::collector::Collector::collect_segment::hb34a08877b4100b3
  29:     0x55cc778eba05 - tantivy::core::searcher::Searcher::search_with_executor::{{closure}}::hd1d71bd9d0a82cab
  30:     0x55cc779477f4 - tantivy::core::executor::Executor::map::{{closure}}::{{closure}}::h491f8d729ab9503a
  31:     0x55cc778b965a - rayon_core::scope::Scope::spawn::{{closure}}::{{closure}}::hfc071114a04b539e
  32:     0x55cc778f1d21 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb92eff675012b026
  33:     0x55cc778bcc07 - std::panicking::try::do_call::h0c530d4775b07e10
  34:     0x55cc778d363d - __rust_try
  35:     0x55cc778bbefc - std::panicking::try::h809350467d037880
  36:     0x55cc778f5443 - std::panic::catch_unwind::h0af775eeffca1588
  37:     0x55cc77938af0 - rayon_core::unwind::halt_unwinding::he5904607d2b275c5
  38:     0x55cc778b9af3 - rayon_core::scope::ScopeBase::execute_job_closure::h0ba2e5b563bb952e
  39:     0x55cc778b99b3 - rayon_core::scope::ScopeBase::execute_job::h7661885e2b0ab21c
  40:     0x55cc778b9550 - rayon_core::scope::Scope::spawn::{{closure}}::h9047f14fb9349417
  41:     0x55cc7788c270 - <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute::hadee723bd17e74fd
  42:     0x55cc77e936fa - rayon_core::job::JobRef::execute::he05b3a828cf3180c
  43:     0x55cc77e87950 - rayon_core::registry::WorkerThread::execute::h39978e106fa9aee3
  44:     0x55cc77e876e9 - rayon_core::registry::WorkerThread::wait_until_cold::hddc9141b38d23114
  45:     0x55cc77e874d1 - rayon_core::registry::WorkerThread::wait_until::h1f071a720f74886b
  46:     0x55cc77e880ec - rayon_core::registry::main_loop::h0779a594efce4596
  47:     0x55cc77e85660 - rayon_core::registry::ThreadBuilder::run::h0f55c4581c3ef739
  48:     0x55cc77e85b41 - <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}::h260282579e9cdd9a
  49:     0x55cc77e9eda0 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdfa45e30ca774009
  50:     0x55cc77e973c1 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hc00c1b2a4bfda637
  51:     0x55cc77e889c3 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he33d631fa919e4e4
  52:     0x55cc77e8ba6a - std::panicking::try::do_call::ha8f9f82dcfa1aca3
  53:     0x55cc77e8cbad - __rust_try
  54:     0x55cc77e8b8dc - std::panicking::try::hb23236c4c25e74d1
  55:     0x55cc77e894a3 - std::panic::catch_unwind::h6eb96cb948319564
  56:     0x55cc77e971bb - std::thread::Builder::spawn_unchecked::{{closure}}::hb1d8e65d25dc32b5
  57:     0x55cc77e8f337 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1fa125ec4e37baf4
  58:     0x55cc7853ddea - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hcf205bcf9b46c587
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
  59:     0x55cc7853ddea - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2d53e2246128f5d8
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
  60:     0x55cc7853ddea - std::sys::unix::thread::Thread::new::thread_start::h3b6d8a0cd87a87c6
                               at src/libstd/sys/unix/thread.rs:87
  61:     0x7f79d7d0b609 - start_thread
  62:     0x7f79d7c17103 - __clone
  63:                0x0 - <unknown>
```

**Comment by fulmicoton** [comment]
Do I have code you can share to help me reproduce?

**Comment by ppodolsky** [comment]
Here it is:
Cargo.toml
```
[package]

name = "hello_world"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]

[dependencies]
tantivy = { git = "https://github.com/tantivy-search/tantivy", branch = "master"}
tempdir = "0.3.7"
```
main.rs
```
#[macro_use]
extern crate tantivy;
extern crate tempdir;
use tantivy::collector::TopDocs;
use tantivy::query::QueryParser;
use tantivy::schema::*;
use tantivy::Index;
use tantivy::ReloadPolicy;
use tempdir::TempDir;

fn main() -> tantivy::Result<()> {
    let index_path = TempDir::new("tantivy_example_dir")?;
    let mut schema_builder = Schema::builder();
    schema_builder.add_text_field("title", TEXT | STORED);
    schema_builder.add_i64_field("year", FAST | INDEXED | STORED);
    let schema = schema_builder.build();
    let index = Index::create_in_dir(&index_path, schema.clone())?;
    let mut index_writer = index.writer(50_000_000)?;
    let title = schema.get_field("title").unwrap();
    let year = schema.get_field("year").unwrap();

    index_writer.add_document(doc!(
        title => "hemoglobin blood",
        year => 1990 as i64
    ));

    index_writer.commit()?;

    let reader = index
        .reader_builder()
        .reload_policy(ReloadPolicy::OnCommit)
        .try_into()?;

    let searcher = reader.searcher();
    let query_parser = QueryParser::for_index(&index, vec![title]);
    let query = query_parser.parse_query("hemoglobin AND year:[1970 TO 1990]")?;
    let top_docs = searcher.search(&query, &TopDocs::with_limit(10))?;
    for (_score, doc_address) in top_docs {
        let retrieved_doc = searcher.doc(doc_address)?;
        println!("{}", schema.to_json(&retrieved_doc));
    }
    Ok(())
}
```
But everything works on tantivy = 0.12.0

**Comment by ppodolsky** [comment]
Bisection showed that this behavior has been introduced in e25284bafe76622cc075f015f3dd009cbb2bab11

**Comment by fulmicoton** [comment]
Thanks ! Yes there has been massive change in master. Your test will be
very useful.

**Comment by fulmicoton** [comment]
The fix is on the way. It should be merged in master today.

**Comment by ppodolsky** [comment]
Awesome!

**Comment by fulmicoton** [comment]
Sorry not delivered yet. I'm waiting for CI to finish

**Comment by ppodolsky** [comment]
Yep, I'm just spying on the opened PR, do not worry.
